/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostRouteImport } from './routes/post'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NgoNgoIdRouteImport } from './routes/ngo.$ngoId'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoNgoIdRoute = NgoNgoIdRouteImport.update({
  id: '/ngo/$ngoId',
  path: '/ngo/$ngoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/tracker': typeof TrackerRoute
  '/ngo/$ngoId': typeof NgoNgoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/tracker': typeof TrackerRoute
  '/ngo/$ngoId': typeof NgoNgoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/tracker': typeof TrackerRoute
  '/ngo/$ngoId': typeof NgoNgoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/b2b'
    | '/dashboard'
    | '/feed'
    | '/help'
    | '/notifications'
    | '/post'
    | '/profile'
    | '/tasks'
    | '/tracker'
    | '/ngo/$ngoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/b2b'
    | '/dashboard'
    | '/feed'
    | '/help'
    | '/notifications'
    | '/post'
    | '/profile'
    | '/tasks'
    | '/tracker'
    | '/ngo/$ngoId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/b2b'
    | '/dashboard'
    | '/feed'
    | '/help'
    | '/notifications'
    | '/post'
    | '/profile'
    | '/tasks'
    | '/tracker'
    | '/ngo/$ngoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  B2bRoute: typeof B2bRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  HelpRoute: typeof HelpRoute
  NotificationsRoute: typeof NotificationsRoute
  PostRoute: typeof PostRoute
  ProfileRoute: typeof ProfileRoute
  TasksRoute: typeof TasksRoute
  TrackerRoute: typeof TrackerRoute
  NgoNgoIdRoute: typeof NgoNgoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/$ngoId': {
      id: '/ngo/$ngoId'
      path: '/ngo/$ngoId'
      fullPath: '/ngo/$ngoId'
      preLoaderRoute: typeof NgoNgoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  B2bRoute: B2bRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  HelpRoute: HelpRoute,
  NotificationsRoute: NotificationsRoute,
  PostRoute: PostRoute,
  ProfileRoute: ProfileRoute,
  TasksRoute: TasksRoute,
  TrackerRoute: TrackerRoute,
  NgoNgoIdRoute: NgoNgoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
